version: 2.1
executors:
  dotnetcoreexecutor:
    docker:
      - image: microsoft/dotnet:2.2-sdk
jobs:
  build:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: dotnet build Source/Source.csproj
  test:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: dotnet test
  code_coverage:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: >
          dotnet test 
          /p:CollectCoverage=true 
          /p:Include=[ProtoStar.DependencyInjection]*
          /p:Threshold=95
  deploy:
    executor: dotnetcoreexecutor
    steps:
      - checkout
      - run: >
          dotnet pack
          Source/Source.csproj
          -c Release
          --include-source
          --include-symbols
          -o ../nuget
      - run: >
          dotnet nuget push 
          nuget/*.nupkg
          -s https://api.nuget.org/v3/index.json
          -k ${NUGET_API_KEY}

workflows:
  version: 2.1
  build_test_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - code_coverage:
          requires:
            - test
      - deploy:
          requires:
            - code_coverage
          filters:
            branches:
              only:
                - master